name:                cToHtml
version:             0.0.0.1
author:              "Georgi Lyubenov"
maintainer:          "godzbanebane@gmail.com"

description:         Lex c using clex and then output white coloured C.

dependencies:
- base >= 4.7 && < 5
- clex
- lucid
- bytestring
- text

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror

executables:
  cToHtml:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cToHtml
