using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wizard
{
    public enum TokenType
    {
        BitwiseAnd,
        BitwiseNot,
        BitwiseOr,
        BitwiseXor,
        Colon,
        Comma,
        Division,
        Dot,
        LeftBrace,
        LeftParenthesis,
        LeftSquareBracket,
        Minus,
        Modulo,
        Newline,
        Plus,
        QuestionMark,
        RightBrace,
        RightParenthesis,
        RightSquareBracket,
        Semicolon,
        Star,
        Tab,
        Whitespace,

        // One or two character tokens
        Bang,
        BangEqual,
        BitwiseAndEqual,
        BitwiseOrEqual,
        BitwiseXorEqual,
        DivideEqual,
        DoubleBang,
        DoubleStar,
        DoubleStarEqual,
        Equal,
        EqualEqual,
        Greater,
        GreaterEqual,
        PlusEqual,
        PlusPlus,
        LeftShift,
        LeftShiftEqual,
        LogicalAnd,
        LogicalOr,
        Less,
        LessEqual,
        StarEqual,
        MinusEqual,
        MinusMinus,
        ModuloEqual,
        RightShift,
        RightShiftEqual,
        StrictEqual,
        StrictNotEqual,

        Identifier,
        Number,
        String,

        // Keywords. ECMAScript 2015
        Break,
        Case,
        Catch,
        Class,
        Const,
        Continue,
        Debugger,
        Default,
        Delete,
        Do,
        Else,
        Export,
        Extends,
        Finally,
        For,
        Function,
        If,
        Import,
        In,
        Instanceof,
        Let,
        New,
        Return,
        Super,
        Switch,
        This,
        Throw,
        Try,
        Typeof,
        Var,
        Void,
        While,
        With,
        Yield,
        Null,
        Undefined,
        True,
        False,


        Eof,

    }

}
