/* Generated by re2c 1.1.1 on Thu Nov 15 10:01:26 2018 */
#line 1 "lexer.re"
#include <iostream>

#include "lexer.hpp"

#include "token.hpp"

namespace SpasmImpl
{
namespace ASM
{
//! Namespace for all lexical analisys classes
namespace Lexer
{
Lexer::Lexer(std::istream& _file, size_t _buffer_size)
    : file(&_file), buffer_size(_buffer_size), state(unsigned(-1)), lineno(0)
{
    buffer = new char[buffer_size];
    cursor = limit = marker = token_start = NULL;
}

Lexer::~Lexer()
{
    delete[] buffer;
}

bool Lexer::tokenize(TokenStream& ts)
{
#line 43 "lexer.re"

    while (1)
    {
#line 41 "lexer.cpp"
        {
            char yych;
            if ((limit - cursor) < 6)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case 0x00:
                    goto yy2;
                case '\t':
                case ' ':
                    goto yy6;
                case '\n':
                    goto yy9;
                case '-':
                    goto yy11;
                case '0':
                    goto yy12;
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy14;
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'b':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'k':
                case 'n':
                case 'o':
                case 'q':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                case 'a':
                    goto yy19;
                case 'c':
                    goto yy20;
                case 'd':
                    goto yy21;
                case 'j':
                    goto yy22;
                case 'l':
                    goto yy23;
                case 'm':
                    goto yy24;
                case 'p':
                    goto yy25;
                case 'r':
                    goto yy26;
                case 's':
                    goto yy27;
                default:
                    goto yy4;
            }
        yy2:
            ++cursor;
#line 254 "lexer.re"
            {
                ts.push_token(Token(Token::EndInput, lineno));

                break;
            }
#line 125 "lexer.cpp"
        yy4:
            ++cursor;
        yy5:
#line 260 "lexer.re"
        {
            return false;
        }
#line 133 "lexer.cpp"
        yy6:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case '\t':
                case ' ':
                    goto yy6;
                default:
                    goto yy8;
            }
        yy8:
#line 241 "lexer.re"
        {
            token_start = cursor;

            continue;
        }
#line 150 "lexer.cpp"
        yy9:
            ++cursor;
#line 247 "lexer.re"
            {
                ++lineno;
                token_start = cursor;

                continue;
            }
#line 160 "lexer.cpp"
        yy11:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                    goto yy28;
                default:
                    goto yy5;
            }
        yy12:
            yych = *(marker = ++cursor);
            switch (yych)
            {
                case 'X':
                case 'x':
                    goto yy29;
                default:
                    goto yy13;
            }
        yy13:
#line 59 "lexer.re"
        {
            ts.push_token(Token(Token::Integer, lineno, token_start, cursor));
            token_start = cursor;

            continue;
        }
#line 183 "lexer.cpp"
        yy14:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy14;
                default:
                    goto yy13;
            }
        yy16:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
        yy17:
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy18;
            }
        yy18:
#line 233 "lexer.re"
        {
            ts.push_token(Token(Token::Ident, lineno, token_start, cursor));
            token_start = cursor;

            continue;
        }
#line 281 "lexer.cpp"
        yy19:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                    goto yy31;
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy33;
                case 'd':
                    goto yy35;
                default:
                    goto yy17;
            }
        yy20:
            yych = *++cursor;
            switch (yych)
            {
                case 'a':
                    goto yy36;
                case 'o':
                    goto yy37;
                default:
                    goto yy17;
            }
        yy21:
            yych = *++cursor;
            switch (yych)
            {
                case 'i':
                    goto yy38;
                case 'u':
                    goto yy39;
                default:
                    goto yy17;
            }
        yy22:
            yych = *++cursor;
            switch (yych)
            {
                case 'm':
                    goto yy40;
                default:
                    goto yy17;
            }
        yy23:
            yych = *++cursor;
            switch (yych)
            {
                case 'a':
                    goto yy41;
                case 'e':
                    goto yy42;
                default:
                    goto yy17;
            }
        yy24:
            yych = *++cursor;
            switch (yych)
            {
                case 'o':
                    goto yy43;
                case 'u':
                    goto yy44;
                default:
                    goto yy17;
            }
        yy25:
            yych = *++cursor;
            switch (yych)
            {
                case 'o':
                    goto yy45;
                case 'r':
                    goto yy46;
                case 'u':
                    goto yy47;
                default:
                    goto yy17;
            }
        yy26:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                    goto yy48;
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy50;
                case 'e':
                    goto yy52;
                default:
                    goto yy17;
            }
        yy27:
            yych = *++cursor;
            switch (yych)
            {
                case 'u':
                    goto yy53;
                default:
                    goto yy17;
            }
        yy28:
            ++cursor;
            goto yy13;
        yy29:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                    goto yy54;
                default:
                    goto yy30;
            }
        yy30:
            cursor = marker;
            goto yy13;
        yy31:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy32;
            }
        yy32:
#line 74 "lexer.re"
        {
            Token t(Token::Integer, lineno, token_start + 1, cursor);
            t.set_int(-t.value_int());
            ts.push_token(t);
            token_start = cursor;
            continue;
        }
#line 473 "lexer.cpp"
        yy33:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy33;
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy32;
            }
        yy35:
            yych = *++cursor;
            switch (yych)
            {
                case 'd':
                    goto yy57;
                default:
                    goto yy17;
            }
        yy36:
            yych = *++cursor;
            switch (yych)
            {
                case 'l':
                    goto yy59;
                default:
                    goto yy17;
            }
        yy37:
            yych = *++cursor;
            switch (yych)
            {
                case 'n':
                    goto yy60;
                default:
                    goto yy17;
            }
        yy38:
            yych = *++cursor;
            switch (yych)
            {
                case 'v':
                    goto yy61;
                default:
                    goto yy17;
            }
        yy39:
            yych = *++cursor;
            switch (yych)
            {
                case 'p':
                    goto yy63;
                default:
                    goto yy17;
            }
        yy40:
            yych = *++cursor;
            switch (yych)
            {
                case 'p':
                    goto yy65;
                default:
                    goto yy17;
            }
        yy41:
            yych = *++cursor;
            switch (yych)
            {
                case 'b':
                    goto yy67;
                default:
                    goto yy17;
            }
        yy42:
            yych = *++cursor;
            switch (yych)
            {
                case 'q':
                    goto yy68;
                case 's':
                    goto yy70;
                default:
                    goto yy17;
            }
        yy43:
            yych = *++cursor;
            switch (yych)
            {
                case 'd':
                    goto yy71;
                default:
                    goto yy17;
            }
        yy44:
            yych = *++cursor;
            switch (yych)
            {
                case 'l':
                    goto yy73;
                default:
                    goto yy17;
            }
        yy45:
            yych = *++cursor;
            switch (yych)
            {
                case 'p':
                    goto yy75;
                default:
                    goto yy17;
            }
        yy46:
            yych = *++cursor;
            switch (yych)
            {
                case 'i':
                    goto yy77;
                default:
                    goto yy17;
            }
        yy47:
            yych = *++cursor;
            switch (yych)
            {
                case 's':
                    goto yy78;
                default:
                    goto yy17;
            }
        yy48:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy49;
            }
        yy49:
#line 67 "lexer.re"
        {
            ts.push_token(
                Token(Token::Integer, lineno, token_start + 1, cursor));
            token_start = cursor;

            continue;
        }
#line 700 "lexer.cpp"
        yy50:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy50;
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy49;
            }
        yy52:
            yych = *++cursor;
            switch (yych)
            {
                case 'a':
                    goto yy79;
                case 't':
                    goto yy80;
                default:
                    goto yy17;
            }
        yy53:
            yych = *++cursor;
            switch (yych)
            {
                case 'b':
                    goto yy82;
                default:
                    goto yy17;
            }
        yy54:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                    goto yy54;
                default:
                    goto yy56;
            }
        yy56:
#line 83 "lexer.re"
        {
            ts.push_token(Token(Token::XInteger, lineno, token_start, cursor));
            token_start = cursor;

            continue;
        }
#line 822 "lexer.cpp"
        yy57:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy58;
            }
        yy58:
#line 137 "lexer.re"
        {
            ts.push_token(Token(Token::Add, lineno));
            token_start = cursor;

            continue;
        }
#line 899 "lexer.cpp"
        yy59:
            yych = *++cursor;
            switch (yych)
            {
                case 'l':
                    goto yy84;
                default:
                    goto yy17;
            }
        yy60:
            yych = *++cursor;
            switch (yych)
            {
                case 's':
                    goto yy86;
                default:
                    goto yy17;
            }
        yy61:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy62;
            }
        yy62:
#line 158 "lexer.re"
        {
            ts.push_token(Token(Token::Div, lineno));
            token_start = cursor;

            continue;
        }
#line 988 "lexer.cpp"
        yy63:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy64;
            }
        yy64:
#line 116 "lexer.re"
        {
            ts.push_token(Token(Token::Dup, lineno));
            token_start = cursor;

            continue;
        }
#line 1065 "lexer.cpp"
        yy65:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                case 'f':
                    goto yy87;
                case 't':
                    goto yy89;
                default:
                    goto yy66;
            }
        yy66:
#line 186 "lexer.re"
        {
            ts.push_token(Token(Token::Jump, lineno));
            token_start = cursor;

            continue;
        }
#line 1142 "lexer.cpp"
        yy67:
            yych = *++cursor;
            switch (yych)
            {
                case 'e':
                    goto yy91;
                default:
                    goto yy17;
            }
        yy68:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy69;
            }
        yy69:
#line 213 "lexer.re"
        {
            ts.push_token(Token(Token::LessEq, lineno));
            token_start = cursor;

            continue;
        }
#line 1225 "lexer.cpp"
        yy70:
            yych = *++cursor;
            switch (yych)
            {
                case 's':
                    goto yy92;
                default:
                    goto yy17;
            }
        yy71:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy72;
            }
        yy72:
#line 165 "lexer.re"
        {
            ts.push_token(Token(Token::Mod, lineno));
            token_start = cursor;

            continue;
        }
#line 1308 "lexer.cpp"
        yy73:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy74;
            }
        yy74:
#line 151 "lexer.re"
        {
            ts.push_token(Token(Token::Mul, lineno));
            token_start = cursor;

            continue;
        }
#line 1385 "lexer.cpp"
        yy75:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                case 'r':
                    goto yy94;
                default:
                    goto yy76;
            }
        yy76:
#line 103 "lexer.re"
        {
            ts.push_token(Token(Token::Pop, lineno));
            token_start = cursor;

            continue;
        }
#line 1462 "lexer.cpp"
        yy77:
            yych = *++cursor;
            switch (yych)
            {
                case 'n':
                    goto yy96;
                default:
                    goto yy17;
            }
        yy78:
            yych = *++cursor;
            switch (yych)
            {
                case 'h':
                    goto yy97;
                default:
                    goto yy17;
            }
        yy79:
            yych = *++cursor;
            switch (yych)
            {
                case 'd':
                    goto yy99;
                default:
                    goto yy17;
            }
        yy80:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy81;
            }
        yy81:
#line 206 "lexer.re"
        {
            ts.push_token(Token(Token::Ret, lineno));
            token_start = cursor;

            continue;
        }
#line 1557 "lexer.cpp"
        yy82:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy83;
            }
        yy83:
#line 144 "lexer.re"
        {
            ts.push_token(Token(Token::Sub, lineno));
            token_start = cursor;

            continue;
        }
#line 1634 "lexer.cpp"
        yy84:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy85;
            }
        yy85:
#line 199 "lexer.re"
        {
            ts.push_token(Token(Token::Call, lineno));
            token_start = cursor;

            continue;
        }
#line 1711 "lexer.cpp"
        yy86:
            yych = *++cursor;
            switch (yych)
            {
                case 't':
                    goto yy101;
                default:
                    goto yy17;
            }
        yy87:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy88;
            }
        yy88:
#line 179 "lexer.re"
        {
            ts.push_token(Token(Token::JumpF, lineno));
            token_start = cursor;

            continue;
        }
#line 1794 "lexer.cpp"
        yy89:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy90;
            }
        yy90:
#line 172 "lexer.re"
        {
            ts.push_token(Token(Token::JumpT, lineno));
            token_start = cursor;

            continue;
        }
#line 1871 "lexer.cpp"
        yy91:
            yych = *++cursor;
            switch (yych)
            {
                case 'l':
                    goto yy103;
                default:
                    goto yy17;
            }
        yy92:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy93;
            }
        yy93:
#line 219 "lexer.re"
        {
            ts.push_token(Token(Token::Less, lineno));
            token_start = cursor;

            continue;
        }
#line 1954 "lexer.cpp"
        yy94:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy95;
            }
        yy95:
#line 109 "lexer.re"
        {
            ts.push_token(Token(Token::PopTo, lineno));
            token_start = cursor;

            continue;
        }
#line 2031 "lexer.cpp"
        yy96:
            yych = *++cursor;
            switch (yych)
            {
                case 't':
                    goto yy105;
                default:
                    goto yy17;
            }
        yy97:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                case 'r':
                    goto yy107;
                default:
                    goto yy98;
            }
        yy98:
#line 97 "lexer.re"
        {
            ts.push_token(Token(Token::Push, lineno));
            token_start = cursor;

            continue;
        }
#line 2114 "lexer.cpp"
        yy99:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy100;
            }
        yy100:
#line 123 "lexer.re"
        {
            ts.push_token(Token(Token::Read, lineno));
            token_start = cursor;

            continue;
        }
#line 2191 "lexer.cpp"
        yy101:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy102;
            }
        yy102:
#line 192 "lexer.re"
        {
            ts.push_token(Token(Token::Const, lineno));
            token_start = cursor;

            continue;
        }
#line 2268 "lexer.cpp"
        yy103:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy104;
            }
        yy104:
#line 226 "lexer.re"
        {
            ts.push_token(Token(Token::Label, lineno));
            token_start = cursor;

            continue;
        }
#line 2345 "lexer.cpp"
        yy105:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy106;
            }
        yy106:
#line 130 "lexer.re"
        {
            ts.push_token(Token(Token::Print, lineno));
            token_start = cursor;

            continue;
        }
#line 2422 "lexer.cpp"
        yy107:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy16;
                default:
                    goto yy108;
            }
        yy108:
#line 91 "lexer.re"
        {
            ts.push_token(Token(Token::PushFrom, lineno));
            token_start = cursor;

            continue;
        }
#line 2499 "lexer.cpp"
        }
#line 264 "lexer.re"
    }
    return true;
}

/*!
** Fills up the buffer when neccessary.
** Note the buffer is always filled to the maximum, not just the
** number of bytes neccessary for the lexer to continue.
**
** \param nbytes	- the number of bytes
*/

void Lexer::buffer_grow(size_t new_size)
{
    char* new_buffer = new char[new_size];

    std::copy(buffer, limit, new_buffer);

    token_start = new_buffer + (token_start - buffer);
    cursor = new_buffer + (cursor - buffer);
    limit = new_buffer + new_size;

    buffer_size = new_size;

    delete[] buffer;
    buffer = new_buffer;
}

void Lexer::read(size_t nbytes)
{
    if (token_start + nbytes > limit)
    {  // we need larger buffer
        buffer_grow(token_start - buffer + nbytes);
    }

    std::copy(token_start, limit, buffer);
    cursor -= token_start - buffer;
    char* old_limit = limit - (token_start - buffer);
    token_start = buffer;

    file->read(old_limit, limit - old_limit);
    if (file->eof())
    {
        size_t bytes = file->gcount();
        std::fill(old_limit + bytes, limit, '\0');
    }
}

void Lexer::buffer_init()
{
    file->read(buffer, buffer_size);
    if (file->eof())
    {
        size_t bytes = file->gcount();
        std::fill(buffer + bytes, buffer + buffer_size, '\0');
    }

    cursor = marker = token_start = buffer;
    limit = buffer + buffer_size;
}

}  // namespace Lexer

}  // namespace ASM
}  // namespace SpasmImpl
