/* Generated by re2c 1.1.1 on Thu Nov 22 14:23:32 2018 */
#line 1 "lexer.re"
#include <iostream>

#include "lexer.hpp"

#include "token.hpp"

namespace SpasmImpl
{
namespace ASM
{
//! Namespace for all lexical analisys classes
namespace Lexer
{
Lexer::Lexer(std::istream& _file, size_t _buffer_size)
    : file(&_file), buffer_size(_buffer_size), state(unsigned(-1)), lineno(0)
{
    buffer = new char[buffer_size];
    cursor = limit = marker = token_start = NULL;
}

Lexer::~Lexer()
{
    delete[] buffer;
}

bool Lexer::tokenize(TokenStream& ts)
{
#line 43 "lexer.re"

    while (1)
    {
#line 41 "lexer.cpp"
        {
            char yych;
            if ((limit - cursor) < 6)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case 0x00:
                    goto yy2;
                case '\n':
                    goto yy6;
                case ' ':
                    goto yy8;
                case '#':
                    goto yy11;
                case '-':
                    goto yy13;
                case '0':
                    goto yy14;
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy16;
                case ':':
                    goto yy18;
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'b':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'k':
                case 'n':
                case 'o':
                case 'q':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                case 'a':
                    goto yy23;
                case 'c':
                    goto yy24;
                case 'd':
                    goto yy25;
                case 'j':
                    goto yy26;
                case 'l':
                    goto yy27;
                case 'm':
                    goto yy28;
                case 'p':
                    goto yy29;
                case 'r':
                    goto yy30;
                case 's':
                    goto yy31;
                default:
                    goto yy4;
            }
        yy2:
            ++cursor;
#line 274 "lexer.re"
            {
                ts.push_token(Token(Token::EndInput, lineno));

                break;
            }
#line 126 "lexer.cpp"
        yy4:
            ++cursor;
        yy5:
#line 280 "lexer.re"
        {
            return false;
        }
#line 134 "lexer.cpp"
        yy6:
            ++cursor;
#line 267 "lexer.re"
            {
                ++lineno;
                token_start = cursor;

                continue;
            }
#line 144 "lexer.cpp"
        yy8:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case ' ':
                    goto yy8;
                default:
                    goto yy10;
            }
        yy10:
#line 251 "lexer.re"
        {
            token_start = cursor;

            continue;
        }
#line 160 "lexer.cpp"
        yy11:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case '\n':
                    goto yy32;
                default:
                    goto yy11;
            }
        yy13:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                    goto yy34;
                default:
                    goto yy5;
            }
        yy14:
            yych = *(marker = ++cursor);
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case ':':
                    goto yy36;
                case 'X':
                case 'x':
                    goto yy38;
                default:
                    goto yy15;
            }
        yy15:
#line 60 "lexer.re"
        {
            ts.push_token(Token(Token::Integer, lineno, token_start, cursor));
            token_start = cursor;

            continue;
        }
#line 202 "lexer.cpp"
        yy16:
            marker = ++cursor;
            if ((limit - cursor) < 2)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case '.':
                    goto yy39;
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy16;
                case ':':
                    goto yy18;
                default:
                    goto yy15;
            }
        yy18:
            ++cursor;
#line 256 "lexer.re"
            {
                token_start = cursor;

                continue;
            }
#line 230 "lexer.cpp"
        yy20:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
        yy21:
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy22;
            }
        yy22:
#line 243 "lexer.re"
        {
            ts.push_token(Token(Token::Ident, lineno, token_start, cursor));
            token_start = cursor;

            continue;
        }
#line 311 "lexer.cpp"
        yy23:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                    goto yy40;
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy42;
                case 'd':
                    goto yy44;
                default:
                    goto yy21;
            }
        yy24:
            yych = *++cursor;
            switch (yych)
            {
                case 'a':
                    goto yy45;
                case 'o':
                    goto yy46;
                default:
                    goto yy21;
            }
        yy25:
            yych = *++cursor;
            switch (yych)
            {
                case 'i':
                    goto yy47;
                case 'u':
                    goto yy48;
                default:
                    goto yy21;
            }
        yy26:
            yych = *++cursor;
            switch (yych)
            {
                case 'm':
                    goto yy49;
                default:
                    goto yy21;
            }
        yy27:
            yych = *++cursor;
            switch (yych)
            {
                case 'a':
                    goto yy50;
                case 'e':
                    goto yy51;
                default:
                    goto yy21;
            }
        yy28:
            yych = *++cursor;
            switch (yych)
            {
                case 'o':
                    goto yy52;
                case 'u':
                    goto yy53;
                default:
                    goto yy21;
            }
        yy29:
            yych = *++cursor;
            switch (yych)
            {
                case 'o':
                    goto yy54;
                case 'r':
                    goto yy55;
                case 'u':
                    goto yy56;
                default:
                    goto yy21;
            }
        yy30:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                    goto yy57;
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy59;
                case 'e':
                    goto yy61;
                default:
                    goto yy21;
            }
        yy31:
            yych = *++cursor;
            switch (yych)
            {
                case 'u':
                    goto yy62;
                default:
                    goto yy21;
            }
        yy32:
            ++cursor;
#line 261 "lexer.re"
            {
                ++lineno;
                token_start = cursor;

                continue;
            }
#line 401 "lexer.cpp"
        yy34:
            ++cursor;
            goto yy15;
        yy35:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
        yy36:
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy35;
                case ':':
                    goto yy18;
                default:
                    goto yy37;
            }
        yy37:
            cursor = marker;
            goto yy15;
        yy38:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                    goto yy63;
                default:
                    goto yy37;
            }
        yy39:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                    goto yy66;
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy68;
                default:
                    goto yy37;
            }
        yy40:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy41;
            }
        yy41:
#line 84 "lexer.re"
        {
            Token t(Token::Integer, lineno, token_start + 1, cursor);
            t.set_int(-t.value_int());
            ts.push_token(t);
            token_start = cursor;
            continue;
        }
#line 547 "lexer.cpp"
        yy42:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy42;
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy41;
            }
        yy44:
            yych = *++cursor;
            switch (yych)
            {
                case 'd':
                    goto yy70;
                default:
                    goto yy21;
            }
        yy45:
            yych = *++cursor;
            switch (yych)
            {
                case 'l':
                    goto yy72;
                default:
                    goto yy21;
            }
        yy46:
            yych = *++cursor;
            switch (yych)
            {
                case 'n':
                    goto yy73;
                default:
                    goto yy21;
            }
        yy47:
            yych = *++cursor;
            switch (yych)
            {
                case 'v':
                    goto yy74;
                default:
                    goto yy21;
            }
        yy48:
            yych = *++cursor;
            switch (yych)
            {
                case 'p':
                    goto yy76;
                default:
                    goto yy21;
            }
        yy49:
            yych = *++cursor;
            switch (yych)
            {
                case 'p':
                    goto yy78;
                default:
                    goto yy21;
            }
        yy50:
            yych = *++cursor;
            switch (yych)
            {
                case 'b':
                    goto yy80;
                default:
                    goto yy21;
            }
        yy51:
            yych = *++cursor;
            switch (yych)
            {
                case 'q':
                    goto yy81;
                case 's':
                    goto yy83;
                default:
                    goto yy21;
            }
        yy52:
            yych = *++cursor;
            switch (yych)
            {
                case 'd':
                    goto yy84;
                default:
                    goto yy21;
            }
        yy53:
            yych = *++cursor;
            switch (yych)
            {
                case 'l':
                    goto yy86;
                default:
                    goto yy21;
            }
        yy54:
            yych = *++cursor;
            switch (yych)
            {
                case 'p':
                    goto yy88;
                default:
                    goto yy21;
            }
        yy55:
            yych = *++cursor;
            switch (yych)
            {
                case 'i':
                    goto yy90;
                default:
                    goto yy21;
            }
        yy56:
            yych = *++cursor;
            switch (yych)
            {
                case 's':
                    goto yy91;
                default:
                    goto yy21;
            }
        yy57:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy58;
            }
        yy58:
#line 77 "lexer.re"
        {
            ts.push_token(
                Token(Token::Integer, lineno, token_start + 1, cursor));
            token_start = cursor;

            continue;
        }
#line 774 "lexer.cpp"
        yy59:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy59;
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy58;
            }
        yy61:
            yych = *++cursor;
            switch (yych)
            {
                case 'a':
                    goto yy92;
                case 't':
                    goto yy93;
                default:
                    goto yy21;
            }
        yy62:
            yych = *++cursor;
            switch (yych)
            {
                case 'b':
                    goto yy95;
                default:
                    goto yy21;
            }
        yy63:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                    goto yy63;
                default:
                    goto yy65;
            }
        yy65:
#line 93 "lexer.re"
        {
            ts.push_token(Token(Token::XInteger, lineno, token_start, cursor));
            token_start = cursor;

            continue;
        }
#line 896 "lexer.cpp"
        yy66:
            ++cursor;
        yy67:
#line 68 "lexer.re"
        {
            ts.push_token(
                Token(Token::FloatingPoint, lineno, token_start, cursor));
            token_start = cursor;

            continue;
        }
#line 909 "lexer.cpp"
        yy68:
            ++cursor;
            if (limit <= cursor)
                return true;
            yych = *cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                    goto yy68;
                default:
                    goto yy67;
            }
        yy70:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy71;
            }
        yy71:
#line 147 "lexer.re"
        {
            ts.push_token(Token(Token::Add, lineno));
            token_start = cursor;

            continue;
        }
#line 1003 "lexer.cpp"
        yy72:
            yych = *++cursor;
            switch (yych)
            {
                case 'l':
                    goto yy97;
                default:
                    goto yy21;
            }
        yy73:
            yych = *++cursor;
            switch (yych)
            {
                case 's':
                    goto yy99;
                default:
                    goto yy21;
            }
        yy74:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy75;
            }
        yy75:
#line 168 "lexer.re"
        {
            ts.push_token(Token(Token::Div, lineno));
            token_start = cursor;

            continue;
        }
#line 1092 "lexer.cpp"
        yy76:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy77;
            }
        yy77:
#line 126 "lexer.re"
        {
            ts.push_token(Token(Token::Dup, lineno));
            token_start = cursor;

            continue;
        }
#line 1169 "lexer.cpp"
        yy78:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                case 'f':
                    goto yy100;
                case 't':
                    goto yy102;
                default:
                    goto yy79;
            }
        yy79:
#line 196 "lexer.re"
        {
            ts.push_token(Token(Token::Jump, lineno));
            token_start = cursor;

            continue;
        }
#line 1246 "lexer.cpp"
        yy80:
            yych = *++cursor;
            switch (yych)
            {
                case 'e':
                    goto yy104;
                default:
                    goto yy21;
            }
        yy81:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy82;
            }
        yy82:
#line 223 "lexer.re"
        {
            ts.push_token(Token(Token::LessEq, lineno));
            token_start = cursor;

            continue;
        }
#line 1329 "lexer.cpp"
        yy83:
            yych = *++cursor;
            switch (yych)
            {
                case 's':
                    goto yy105;
                default:
                    goto yy21;
            }
        yy84:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy85;
            }
        yy85:
#line 175 "lexer.re"
        {
            ts.push_token(Token(Token::Mod, lineno));
            token_start = cursor;

            continue;
        }
#line 1412 "lexer.cpp"
        yy86:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy87;
            }
        yy87:
#line 161 "lexer.re"
        {
            ts.push_token(Token(Token::Mul, lineno));
            token_start = cursor;

            continue;
        }
#line 1489 "lexer.cpp"
        yy88:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                case 'r':
                    goto yy107;
                default:
                    goto yy89;
            }
        yy89:
#line 113 "lexer.re"
        {
            ts.push_token(Token(Token::Pop, lineno));
            token_start = cursor;

            continue;
        }
#line 1566 "lexer.cpp"
        yy90:
            yych = *++cursor;
            switch (yych)
            {
                case 'n':
                    goto yy109;
                default:
                    goto yy21;
            }
        yy91:
            yych = *++cursor;
            switch (yych)
            {
                case 'h':
                    goto yy110;
                default:
                    goto yy21;
            }
        yy92:
            yych = *++cursor;
            switch (yych)
            {
                case 'd':
                    goto yy112;
                default:
                    goto yy21;
            }
        yy93:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy94;
            }
        yy94:
#line 216 "lexer.re"
        {
            ts.push_token(Token(Token::Ret, lineno));
            token_start = cursor;

            continue;
        }
#line 1661 "lexer.cpp"
        yy95:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy96;
            }
        yy96:
#line 154 "lexer.re"
        {
            ts.push_token(Token(Token::Sub, lineno));
            token_start = cursor;

            continue;
        }
#line 1738 "lexer.cpp"
        yy97:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy98;
            }
        yy98:
#line 209 "lexer.re"
        {
            ts.push_token(Token(Token::Call, lineno));
            token_start = cursor;

            continue;
        }
#line 1815 "lexer.cpp"
        yy99:
            yych = *++cursor;
            switch (yych)
            {
                case 't':
                    goto yy114;
                default:
                    goto yy21;
            }
        yy100:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy101;
            }
        yy101:
#line 189 "lexer.re"
        {
            ts.push_token(Token(Token::JumpF, lineno));
            token_start = cursor;

            continue;
        }
#line 1898 "lexer.cpp"
        yy102:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy103;
            }
        yy103:
#line 182 "lexer.re"
        {
            ts.push_token(Token(Token::JumpT, lineno));
            token_start = cursor;

            continue;
        }
#line 1975 "lexer.cpp"
        yy104:
            yych = *++cursor;
            switch (yych)
            {
                case 'l':
                    goto yy116;
                default:
                    goto yy21;
            }
        yy105:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy106;
            }
        yy106:
#line 229 "lexer.re"
        {
            ts.push_token(Token(Token::Less, lineno));
            token_start = cursor;

            continue;
        }
#line 2058 "lexer.cpp"
        yy107:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy108;
            }
        yy108:
#line 119 "lexer.re"
        {
            ts.push_token(Token(Token::PopTo, lineno));
            token_start = cursor;

            continue;
        }
#line 2135 "lexer.cpp"
        yy109:
            yych = *++cursor;
            switch (yych)
            {
                case 't':
                    goto yy118;
                default:
                    goto yy21;
            }
        yy110:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                case 'r':
                    goto yy120;
                default:
                    goto yy111;
            }
        yy111:
#line 107 "lexer.re"
        {
            ts.push_token(Token(Token::Push, lineno));
            token_start = cursor;

            continue;
        }
#line 2218 "lexer.cpp"
        yy112:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy113;
            }
        yy113:
#line 133 "lexer.re"
        {
            ts.push_token(Token(Token::Read, lineno));
            token_start = cursor;

            continue;
        }
#line 2295 "lexer.cpp"
        yy114:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy115;
            }
        yy115:
#line 202 "lexer.re"
        {
            ts.push_token(Token(Token::Const, lineno));
            token_start = cursor;

            continue;
        }
#line 2372 "lexer.cpp"
        yy116:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy117;
            }
        yy117:
#line 236 "lexer.re"
        {
            ts.push_token(Token(Token::Label, lineno));
            token_start = cursor;

            continue;
        }
#line 2449 "lexer.cpp"
        yy118:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy119;
            }
        yy119:
#line 140 "lexer.re"
        {
            ts.push_token(Token(Token::Print, lineno));
            token_start = cursor;

            continue;
        }
#line 2526 "lexer.cpp"
        yy120:
            yych = *++cursor;
            switch (yych)
            {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':
                    goto yy20;
                default:
                    goto yy121;
            }
        yy121:
#line 101 "lexer.re"
        {
            ts.push_token(Token(Token::PushFrom, lineno));
            token_start = cursor;

            continue;
        }
#line 2603 "lexer.cpp"
        }
#line 284 "lexer.re"
    }
    return true;
}

/*!
** Fills up the buffer when neccessary.
** Note the buffer is always filled to the maximum, not just the
** number of bytes neccessary for the lexer to continue.
**
** \param nbytes        - the number of bytes
*/

void Lexer::buffer_grow(size_t new_size)
{
    char* new_buffer = new char[new_size];

    std::copy(buffer, limit, new_buffer);

    token_start = new_buffer + (token_start - buffer);
    cursor = new_buffer + (cursor - buffer);
    limit = new_buffer + new_size;

    buffer_size = new_size;

    delete[] buffer;
    buffer = new_buffer;
}

void Lexer::read(size_t nbytes)
{
    if (token_start + nbytes > limit)
    {  // we need larger buffer
        buffer_grow(token_start - buffer + nbytes);
    }

    std::copy(token_start, limit, buffer);
    cursor -= token_start - buffer;
    char* old_limit = limit - (token_start - buffer);
    token_start = buffer;

    file->read(old_limit, limit - old_limit);
    if (file->eof())
    {
        size_t bytes = file->gcount();
        std::fill(old_limit + bytes, limit, '\0');
    }
}

void Lexer::buffer_init()
{
    file->read(buffer, buffer_size);
    if (file->eof())
    {
        size_t bytes = file->gcount();
        std::fill(buffer + bytes, buffer + buffer_size, '\0');
    }

    cursor = marker = token_start = buffer;
    limit = buffer + buffer_size;
}

}  // namespace Lexer

}  // namespace ASM
}  // namespace SpasmImpl
