name:                brainfsck
version:             0.0.0.1
author:              "Georgi Lyubenov"
maintainer:          "godzbanebane@gmail.com"

extra-source-files:
- README.md

description:         brainfsck!

dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring

ghc-options:
- -Werror
- -Wall

library:
  source-dirs: src

executables:
  brainfsck:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainfsck
