name:                clex
version:             0.0.0.1
author:              "Georgi Lyubenov"
maintainer:          "godzbanebane@gmail.com"

description:         Lex C and keep whitespace so I can print it afterwards.

dependencies:
- base >= 4.7 && < 5
- bytestring
- attoparsec
- word8

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror

tests:
  clex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clex
    - QuickCheck
    - hspec
    - bytestring-arbitrary
